CREATE TABLE "TMCR_MENSAJESVISUALIZACION" 
(	
    "MVIIDENTIFICADOR" NUMBER(4,0), 
    "MVIPROCESO" NUMBER(1,0), 
    "MVIESTADO" VARCHAR2(50 CHAR), 
    "MVIABREVIATURA" VARCHAR2(50 CHAR), 
    "MVIMENSAJE" VARCHAR2(400 CHAR), 
    "MVIFECHACREACION" DATE, 
    "MVIUSUARIOCREACION" VARCHAR2(50 CHAR)
)

Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('18',null,'Fallo','INCORRECTO','Se espera un caractér en S o N',to_date('01/11/2022 09:46:49','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('1','1','Exitoso','BE','Búsqueda exacta',to_date('18/10/2022 10:26:42','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('2','2','Exitoso','I','Inserción del registro',to_date('18/10/2022 10:26:42','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('3','3','Exitoso','AR','Actualización del registro',to_date('18/10/2022 10:26:42','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('4','4','Exitoso','BR','Eliminación del registro',to_date('18/10/2022 10:26:42','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('5','5','Exitoso','LT','Listado de todos los registros',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('6','6','Exitoso','BG','Búsqueda genérica',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('7','1','Fallo','BE','Búsqueda exacta, sin resultados',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('8','2','Fallo','I','El registro ya existe en la base de datos',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('9','3','Fallo','AR','El registros NO existe en la base de datos',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('10',null,'Fallo','NULL','Existe valores en NULL, por favor validar',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('11','6','Fallo','BG','No se encontrarón registros',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('12',null,'Fallo','NOCARACTER','El nombre de la variable no cuenta con un carácter tipo cadena',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('13',null,'Fallo','FORANEA','Existe un problema con una llave fóranea',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('14',null,'Fallo','OTROS','substr(''Error: Se presento un error con código ''   || sqlcode   || '' -ERROR- ''  || sqlerrm, 1, 512)',to_date('18/10/2022 10:26:43','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('15',null,'null','EJE','En Ejecución',to_date('18/10/2022 16:59:55','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('16',null,'Fallo','IDCRUD','No existe la acción, o no está habilitado para este proceso',to_date('18/10/2022 17:41:33','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
Insert into TMCR_MENSAJESVISUALIZACION (MVIIDENTIFICADOR,MVIPROCESO,MVIESTADO,MVIABREVIATURA,MVIMENSAJE,MVIFECHACREACION,MVIUSUARIOCREACION) values ('17','4','Exitoso','INACTIVO','Inactivo el registro',to_date('28/10/2022 12:59:55','DD/MM/YYYY HH24:MI:SS'),'AOSILVA');
