CREATE TABLE "TMCR_CLIENTE" 
(	
	"CLIID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLITIPODOCUMENTO" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CLINRODOCUMENTO" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CLINOMBRECOMPLETO" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	"CLITELEFONO" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"CLIDIRECCION" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	"CLIEMAIL" VARCHAR2(200 CHAR),
	"CLIOBSERVACIONES" VARCHAR2(500 CHAR),
	"CLIESTADO" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"CLIFECHAREGISTRO" DATE,
	"CLISUARIOCREACION" VARCHAR2(20 CHAR),
	CONSTRAINT "TMCR_CLIENTE_PK" PRIMARY KEY ("CLIID")
);

Insert into TMCR_CLIENTE (CLIID,CLITIPODOCUMENTO,CLINRODOCUMENTO,CLINOMBRECOMPLETO,CLITELEFONO,CLIDIRECCION,CLIEMAIL,CLIOBSERVACIONES,CLIESTADO,CLIFECHAREGISTRO,CLISUARIOCREACION) values ('1','CEDULA','92589653','ALEJANDRO BUSTAMANTE DIAS','3104582396','CALLE 5 23-45','añejo2563@gmail.com','NA','ACTIVO',to_date('20/02/2024 07:07:30','DD/MM/YYYY HH24:MI:SS'),'ADMIN');
Insert into TMCR_CLIENTE (CLIID,CLITIPODOCUMENTO,CLINRODOCUMENTO,CLINOMBRECOMPLETO,CLITELEFONO,CLIDIRECCION,CLIEMAIL,CLIOBSERVACIONES,CLIESTADO,CLIFECHAREGISTRO,CLISUARIOCREACION) values ('2','CEDULA','102785322','MARIA ANTONELA SILVA VIDAL','3118956389','CALLE 11 89B-12','mariaantonela56897@gmail.com','NA','ACTIVO',to_date('20/02/2024 07:10:07','DD/MM/YYYY HH24:MI:SS'),'ADMIN');

COMMIT;



