  CREATE TABLE "TMIG_USUARIO" ("USUNOMBREUSUARIO" VARCHAR2(100 CHAR), "USUNOMBRE" VARCHAR2(255 CHAR), "USUAPELLIDO" VARCHAR2(255 CHAR), "USUCORREOELECTRONICO" VARCHAR2(255 CHAR), "USUCLAVE" VARCHAR2(100 CHAR), "USUACTIVO" CHAR(1 CHAR), "USUNOTIFICACIONPROCESO" CHAR(1 CHAR), "USUPROCESO" VARCHAR2(30 CHAR), "USUUSUARIOCREACION" VARCHAR2(50 CHAR), "USUFECHACREACION" DATE) ;

   COMMENT ON COLUMN "TMIG_USUARIO"."USUNOMBREUSUARIO" IS 'CÃ³digo identificador del nombre de usuario que la persona usarÃ¡ para loguearse';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUNOMBRE" IS 'Nombre del usuario';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUAPELLIDO" IS 'Apellido del usuario';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUCORREOELECTRONICO" IS 'Correo electrÃ³nico del usuario';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUCLAVE" IS 'ContraseÃ±a del usuario';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUACTIVO" IS 'Indicador de que la persona estÃ¡ activa';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUNOTIFICACIONPROCESO" IS 'Usuario de auditorÃ­a';
   COMMENT ON COLUMN "TMIG_USUARIO"."USUPROCESO" IS 'Fecha de auditorÃ­a';
   COMMENT ON TABLE "TMIG_USUARIO"  IS 'Entidad que se encarga de almacenar los usuarios de la aplicaciÃ³n';
 
Insert into TMIG_USUARIO (USUNOMBREUSUARIO,USUNOMBRE,USUAPELLIDO,USUCORREOELECTRONICO,USUCLAVE,USUACTIVO,USUNOTIFICACIONPROCESO,USUPROCESO,USUUSUARIOCREACION,USUFECHACREACION) 
values ('ADMIN','ADMIN','ADMIN','NA','09spfSv8J5C1Hrqvmq3A1w==','S','S','AMBOS','ADMIN',to_date('15/09/2022 22:22:02','DD/MM/YYYY HH24:MI:SS'));

COMMIT;

