  CREATE TABLE "TMIG_OPCIONMENU" ("OPMID" NUMBER(4,0), "OPMNOMBREOPCION" VARCHAR2(100 CHAR), "OPMURLOPCION" VARCHAR2(200 CHAR), "OPMACTIVO" CHAR(1 CHAR), "OPMUSUARIOCREACION" VARCHAR2(50 CHAR), "OPMFECHACREACION" DATE) ;

   COMMENT ON COLUMN "TMIG_OPCIONMENU"."OPMID" IS 'CÃ³digo identificador de llave primaria';
   COMMENT ON COLUMN "TMIG_OPCIONMENU"."OPMNOMBREOPCION" IS 'Nombre de la opciÃ³n del menÃº';
   COMMENT ON COLUMN "TMIG_OPCIONMENU"."OPMURLOPCION" IS 'URL del menÃº';
   COMMENT ON COLUMN "TMIG_OPCIONMENU"."OPMACTIVO" IS 'Indica si el menÃº estÃ¡ activo en la aplicaciÃ³n';
   COMMENT ON COLUMN "TMIG_OPCIONMENU"."OPMUSUARIOCREACION" IS 'Usuario de auditorÃ­a';
   COMMENT ON COLUMN "TMIG_OPCIONMENU"."OPMFECHACREACION" IS 'Fecha de auditorÃ­a';
   COMMENT ON TABLE "TMIG_OPCIONMENU"  IS 'Entidad que se encarga de almacenar las opciones de los menÃºs de la aplicaciÃ³n';
   
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('6','Prueba1','/url_prueba','N','pruebasUsuarioLogin',to_date('27/10/2022 14:44:32','DD/MM/YYYY HH24:MI:SS'));
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('1','OPCION_1','URL_OPCION_1','N','NEO',to_date('20/09/2022 14:45:58','DD/MM/YYYY HH24:MI:SS'));
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('2','OPCION_2','URL_OPCION_2','S','NEO',to_date('20/09/2022 14:46:03','DD/MM/YYYY HH24:MI:SS'));
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('3','TEST_1','CAMBIO','N','NEO',to_date('20/09/2022 14:46:07','DD/MM/YYYY HH24:MI:SS'));
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('4','OPCION_4','URL_OPCION_4','S','NEO',to_date('20/09/2022 14:46:14','DD/MM/YYYY HH24:MI:SS'));
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('7','Edwin2','/url2','S','pruebasUsuarioLogin',to_date('20/02/2023 16:45:03','DD/MM/YYYY HH24:MI:SS'));
Insert into TMIG_OPCIONMENU (OPMID,OPMNOMBREOPCION,OPMURLOPCION,OPMACTIVO,OPMUSUARIOCREACION,OPMFECHACREACION) values ('5','TEST_1','TEST_1','S','TEST_1',to_date('12/10/2022 09:48:48','DD/MM/YYYY HH24:MI:SS'));

commit;

