/*
 * API D1 aplicación de clientes
 *
 * Api Rest servicios de clientes
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ingenieria@groupware.com.co
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace milescarrental.Application.Models
{ 
    /// <summary>
    /// Dirección en la cual se ordenan los registros solicitados * &#x60;0&#x60; ASC * &#x60;1&#x60; DESC 
    /// </summary>
    [DataContract]
    public partial class ApiPaginationDirection : IEquatable<ApiPaginationDirection>
    { 
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiPaginationDirection {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ApiPaginationDirection)obj);
        }

        /// <summary>
        /// Returns true if ApiPaginationDirection instances are equal
        /// </summary>
        /// <param name="other">Instance of ApiPaginationDirection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiPaginationDirection other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ApiPaginationDirection left, ApiPaginationDirection right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ApiPaginationDirection left, ApiPaginationDirection right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
